import Sidebar from '@/components/shared/Sidebar';
import React from 'react';


export const metadata = {
  title: 'Next js Dashboard',
  description: 'Generated by create next app',
};


const DashboardLayout = ({ children }) => {
  return (
    <div className='flex'>
      <Sidebar></Sidebar>
      <div className="w-full">
        {children}
      </div>
    </div>
  );
};

export default DashboardLayout;